### PR TITLE
Ft profile settings

### PR DESCRIPTION
**Pull request by Heisjabo**
### Overview:
This pull request introduces profile settings management essential middleware functions for user authentication. The changes facilitate efficient handling of profile settings within the application.

### Changes Made:
1. **Profile settings:**
    - Allow users to update their profile info except email

3. **User Authentication Middleware:**
   - Implemented middleware functions to enforce user authentication across relevant routes.

4. **Ownership Validation Middleware:**
   - Added middleware to validate ownership of resources, ensuring users can only modify their own data.
   - Enhances data integrity and security by preventing unauthorized access or modification of sensitive information.

### Fixes and Enhancements:
- Resolved issues with Google Auth signin to ensure smooth authentication flow.
- Improved user experience by allowing profile editing with updates to all fields except email.

### Additional Notes:
These changes are based on the `ft-profile-settings` branch and are essential for implementing profile management features within the application.

Kindly review and merge this pull request at your earliest convenience.

Thank you!

### CODE REVIEW

**Review by niyobertin — APPROVED** [review]
Perfect

**Review by Jovz19200 — APPROVED** [review]
Good work

**Review by yvanddniyo — COMMENTED** [review]
LGTM

**Review by yvanddniyo — COMMENTED** [review]
LGTM

**Pull request merged**
